# configure calculation order
[calculations]
cal_order = "mpirun -np"

# configure the software path
[software_paths]
QE = "/share/home/jinxin/soft/QE/q-e-qe-7.2/bin"
# QE = "/share/home/jinxin/soft/QE/qe-7.0/bin"
python = "/share/home/jinxin/dxy/soft/miniconda39/bin/python"
third_order = "/share/home/jinxin/soft/shengbte/thirdorder"
shengbte = "/share/home/jinxin/soft/shengbte/FourPhonon-main"
perturbo = "/share/home/jinxin/soft/QE/q-e-qe-7.2/perturbo-2.2.0/bin"

#configure the pseudo_paths
[pseudo_paths]
psesudo = "/share/home/jinxin/soft/QE/POT"

# configure the submission scripts
[submit_scripts]
template = """
#!/bin/sh
#PBS -N {job_name}
#PBS -j oe
#PBS -q workq
#PBS -l select=1:ncpus={num_cores}:host={cal_nodes}:mpiprocs={num_cores}
#PBS -V
cd $PBS_O_WORKDIR

echo -n "start time  " > time
export I_MPI_HYDRA_BOOTSTRAP=ssh
date >> time
source /share/intel/2022.2/setvars.sh
module load gcc/10.2.0
"""
